version: "3"

services:
  main:
    image: ghdl/ext:latest
    restart: always
    tty: true
    working_dir: /Zx7E4
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - .:/Zx7E4
